### PR TITLE
Add serialize name for the lipa na mpesa payment body

### PR DESCRIPTION
**Pull request by SefuZeph**
Fixed com.androidstudy.daraja.callback.DarajaException: 400.002.02 : Bad Request - Invalid BusinessShortCode

### CODE REVIEW

**Comment by wangerekaharun** [comment]
Thanks @SefuZeph this has been a long time bug:-) This looks good to me; one least request, can you upload a video of the app with your current implementation?

**Comment by SefuZeph** [comment]
Hello @wangerekaharun pleasure is all mine. Here you go
https://user-images.githubusercontent.com/11628897/213328438-fdd2cc74-0049-4eea-ba97-6e48533e3b2c.mp4

**Review by jumaallan — APPROVED** [review]
Thank you for this fix

**Comment by jumaallan** [comment]
> Thanks @SefuZeph this has been a long time bug:-) This looks good to me; one least request, can you upload a video of the app with your current implementation?

I see where it used to break 😄

**Review by wangerekaharun — APPROVED** [review]

**Pull request merged**
